apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  labels:
    app: flask-app
spec:
  containers:
    - name: flask-container
      image: vishvajitkanase/demo-app
      ports:
        - containerPort: 5000
      env:
        - name: FLASK_ENV
          value: "production"
